---

- name: SCHEMA_REGISTRY | Ensure schema_registry group
  group:
    name: "{{ schema_registry_group }}"
    system: yes
    state: present
  tags:
    - schema_registry_install

- name: SCHEMA_REGISTRY | Ensure schema_registry user
  user:
    name: "{{ schema_registry_user }}"
    group: "{{ schema_registry_group }}"
    home: /bin/false
  tags:
    - schema_registry_install

- name: SCHEMA_REGISTRY | Ensure skeleton paths
  file:
    dest: "{{ item }}"
    owner: "{{ schema_registry_user }}"
    group: "{{ schema_registry_group }}"
    state: directory
  with_items:
    - "{{ schema_registry_skeleton_paths }}"
  tags:
    - schema_registry_install

- name: SCHEMA_REGISTRY | Check schema_registry version
  shell: "{{ schema_registry_check_version }}"
  register: schema_registry_check
  changed_when: false
  ignore_errors: true
  check_mode: no
  tags:
    - schema_registry_install
      
- name: SCHEMA_REGISTRY | Download and extract files in final dir
  unarchive:
    src: "{{ schema_registry_url }}"
    dest: "{{ schema_registry_extracted_path }}"
    remote_src: True
    extra_opts: [--strip-components=1]
  when: schema_registry_force_reinstall or schema_registry_check is failed or schema_registry_version  not in schema_registry_check.stdout
  tags:
    - schema_registry_install