---

- name: SCHEMA_REGISTRY | Install
  include: install.yml
  tags:
    - schema_registry_install
  when: >
    schema_registry_kafkastore_bootstrap_server_hosts is defined
    and schema_registry_kafkastore_bootstrap_server_port is defined

- name: SCHEMA_REGISTRY | Service
  include: service.yml
  tags:
    - schema_registry_service
