---

schema_registry_private_tmp: false
kafka_zookeeper_hosts: 
  - zookeepertest:2181
zookeeper_hosts:
  - host: zookeepertest  # the machine running
    id: 1

kafka_offsets_topic_replication_factor: 1
kafka_transaction_state_log_replication_factor: 1
schema_registry_kafkastore_bootstrap_servers_host: kafka
schema_registry_kafkastore_bootstrap_servers_port: 9092